# Generated by Django 2.2.7 on 2019-11-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDataTablosu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=10000, null=True)),
                ('category', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'test_data',
            },
        ),
    ]
