# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-30 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ekonomi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, null=True)),
                ('content', models.CharField(max_length=10000, null=True)),
                ('url', models.CharField(max_length=10000, null=True)),
                ('keywords', models.CharField(max_length=10000, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('counter', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'ekonomi',
            },
        ),
        migrations.CreateModel(
            name='Politika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, null=True)),
                ('content', models.CharField(max_length=10000, null=True)),
                ('url', models.CharField(max_length=10000, null=True)),
                ('keywords', models.CharField(max_length=10000, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('counter', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'politika',
            },
        ),
        migrations.CreateModel(
            name='Sanat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, null=True)),
                ('content', models.CharField(max_length=10000, null=True)),
                ('url', models.CharField(max_length=10000, null=True)),
                ('keywords', models.CharField(max_length=10000, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('counter', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'sanat',
            },
        ),
        migrations.CreateModel(
            name='Spor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, null=True)),
                ('content', models.CharField(max_length=10000, null=True)),
                ('url', models.CharField(max_length=10000, null=True)),
                ('keywords', models.CharField(max_length=10000, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('counter', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'spor',
            },
        ),
        migrations.CreateModel(
            name='Teknoloji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, null=True)),
                ('content', models.CharField(max_length=10000, null=True)),
                ('url', models.CharField(max_length=10000, null=True)),
                ('keywords', models.CharField(max_length=10000, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('counter', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'teknoloji',
            },
        ),
    ]
